### PR TITLE
Fixing flakey tests

### LINKED ISSUE #601: Flakey tests
These seem to fail most often (the first one the most). Not sure if we can add any more waits or the like to make them less flakey? I've opened a PR #599 to automate the reruns in GitHub Actions.

### LCP 1

[0-3] Error in "onLCP().stops reporting after the document changes to hidden (reportAllChanges === false)"
Error: waitUntil condition timed out after 10000ms
    at async beaconCountIs (file:///Users/runner/work/web-vitals/web-vitals/test/utils/beacons.js:26:3)
    at async Context.<anonymous> (file:///Users/runner/work/web-vitals/web-vitals/test/e2e/onLCP-test.js:283:5)

### INP 1

[0-2] AssertionError in "onINP().attribution.includes LoAF entries if the browser supports it"
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  assert(inp1.attribution.longAnimationFrameEntries.length > 0)
    at Context.<anonymous> (file:///Users/runner/work/web-vitals/web-vitals/test/e2e/onINP-test.js:843:7)

### INP 2

[chrome 134.0.6998.118 mac #0-2] 1) onINP() reports a new interaction after bfcache restore
[chrome 134.0.6998.118 mac #0-2] Expected values to be strictly equal:
+ actual - expected

+ 'good'
- 'needs-improvement'      
      actual expected
      
      'goodneeds-improvement'

### LINKED ISSUE #608: Firefox INP tests disabled
Reminder to myself that in #592 I disabled Firefox INP tests (INP has started to become available in Nightly):

https://github.com/GoogleChrome/web-vitals/blob/3b9acdb1702bf1dbd76f2091cb585619d9d65481/wdio.conf.cjs#L95-L98

This can be re-enabled if https://bugzilla.mozilla.org/show_bug.cgi?id=1960645 is fixed.

### PR DESCRIPTION
**Pull request by tunetheweb**
Fixing flakey tests (especially now Firefox Nightly supports INP so they are even more flakey!)

Fixes #601 
Fixes #608

### CODE REVIEW

**Comment by canova** [comment]
Hmm it looks like these lines are failing now on Firefox:
https://github.com/GoogleChrome/web-vitals/blob/00f78c5c785aaed744784b58e97d2b8b5f5776e1/test/e2e/onINP-test.js#L370-L373

Did you manage to figure out why? It looks weird, considering that we have a 300ms `pointerdown` blocking time above it, here:
https://github.com/GoogleChrome/web-vitals/blob/00f78c5c785aaed744784b58e97d2b8b5f5776e1/test/e2e/onINP-test.js#L353

**Comment by tunetheweb** [comment]
Woo hoo - got them all to pass now!!

Basically it was a combo of either not waiting for the library to load (and reduce the default threshold to 40ms), or having an INP beneath that 104ms.

Solution is it basically wait for the library to load to begin the test.
Or
Do an interaction that takes longer than 104ms so it's in the bugger.

This has been an occasional problem for Chrome, but it seemed to be more consistently wrong for Firefox. Either way making tests less flakey will benefit testing both!

File: test/e2e/onINP-test.js [hunk 1]
```diff
@@ -696,17 +697,18 @@ describe('onINP()', async function () {
...
+      // Wait until the library is loaded and the first paint occurs to ensure
+      // The 40ms event duration is set
+      await webVitalsLoaded();
+      await firstContentfulPaint();
+
       const h1 = await $('h1');
       await simulateUserLikeClick(h1);
 
-      await stubVisibilityChange('hidden');
-
```
Comment (tunetheweb) [inline test/e2e/onINP-test.js:709]: @philipwalton this was weird and this change shouldn't be necessary.

Firefox would often fail to report only 1 (and sometimes none!) with this method. But changing it to `&reportAllChanges=1&reportAllChanges2=1` fixed it.

Since the point of this test wasn't to test the visibilitychange thing I was OK changing it, but it might warrant further investigation to see if there's some other flaw in multiple `onINP` calls in Firefox not playing nice with each other (e.g. the reporting of the first `onINP` prevents the second from getting the callback).

Comment (philipwalton) [reply test/e2e/onINP-test.js:709]: SGTM

File: test/views/inp.njk [hunk 2]
```diff
@@ -118,7 +118,7 @@
       inp.instance = 1;
 
       // Log for easier manual testing.
-      console.log(inp);
+      console.log('INP1', inp);
```
Comment (philipwalton) [inline test/views/inp.njk:121]: Did you want to do this everywhere, or just for INP?

**Review by philipwalton — APPROVED** [review]

File: test/views/inp.njk (hunk 2 above)
Comment (tunetheweb) [reply test/views/inp.njk]: Good point. Fixed em all.
